server:
    #port: 8101
    port: ${PORT:${SERVER_PORT:0}}
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        #hostname: localhost
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Resilience4j - Circuit Breaker

resilience4j:
    circuitbreaker:
        instances:
            carrosCB:
                registerHealthIndicator: true
                slidingWindowSize: 10
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowType: TIME_BASED
                minimumNumberOfCalls: 4
                waitDurationInOpenState: 5s
                failureRateThreshold: 50
                eventConsumerBufferSize: 10
            motosCB:
                registerHealthIndicator: true
                slidingWindowSize: 10
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowType: TIME_BASED
                minimumNumberOfCalls: 4
                waitDurationInOpenState: 5s
                failureRateThreshold: 50
                eventConsumerBufferSize: 10
            todosCB:
                registerHealthIndicator: true
                slidingWindowSize: 10
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowType: TIME_BASED
                minimumNumberOfCalls: 4
                waitDurationInOpenState: 5s
                failureRateThreshold: 50
                eventConsumerBufferSize: 10
spring:
    application:
        name: usuario-service

management:
    tracing:
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
    observations:
        web:
            mvc:
                enabled: true
