# spring.application.name=config-service

server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: config server
                    uri: https://github.com/RaulPesantes/microservicios-tutorial
                    search-paths: config-data
    applications:
        name: config-service

